name: Evaluate Ontology with OQuaRE

on:
  push:
    paths:
      - 'oquare-metrics/ontologies/imports/*.owl'

permissions:
  contents: write

jobs:
  evaluate_ontologies:
    runs-on: ubuntu-latest
    name: Evaluate ontologies
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: OQuaRE module
        uses: tecnomod-um/oquare-metrics@v3.0
        with:
          ontology-folders: 'oquare-metrics/ontologies/imports'
