
on:
  push:
    paths:
      - 'oquare-metrics/ontologies/imports/doid.owl' # Déclencher le workflow lorsqu'il y a des modifications sur doid.owl

jobs:
  evaluate_ontologies:
    runs-on: ubuntu-latest
    name: Evaluate ontologies
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: OQuaRE metrics calculation
        uses: anouar25343/oquare-metrics@v3.0
        with:
          ontology-folders: 'oquare-metrics/ontologies/imports' # Le dossier où se trouve le fichier doid.owl
          ontology-files: 'doid.owl' # Spécifie le fichier à évaluer
          contents-folder: 'oquare-metrics/OQuaRE/archives/ontologies/imports' # Le dossier où les résultats seront enregistrés
          # Ajoutez les autres options de configuration nécessaires ici
