on: [push]

jobs:
  evaluate_ontologies:
    runs-on: ubuntu-latest
    name: Evaluate ontologies
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: OQuaRE metrics calculation
        uses: anouar25343/oquare-metrics@v3.0
        with:
          contents-folder: 'oquare-metrics/OQuaRE/archives/ontologies/imports'
          # Autres options supplémentaires selon les besoins
